### ISSUE TITLE
import function bug

### ISSUE THREAD

**Issue by SeverusYixin** [NFDI4BIOIMAGE/training#193]
Hi @haesleinhuepf, after directly importing your code, with:

# Import the functions from other modules in the same folder
from generate_link_lists import read_yaml_file, load_dataframe
from _github_utilities import get_github_repository  

it shows me as: 

C:\Users\huang\Documents\GitHub\training\scripts>streamlit run appsubmitter.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.26.44.166:8501

Adding nfdi4bioimage.yml
Adding nfdi4bioimage.yml
2024-09-04 13:10:58.472 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\huang\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\huang\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\huang\Documents\GitHub\training\scripts\appsubmitter.py", line 120, in <module>
    unique_tags, unique_types, unique_licenses = get_unique_values_from_yamls(directory_path)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\appsubmitter.py", line 44, in get_unique_values_from_yamls
    df = load_dataframe(resources_dir)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\generate_link_lists.py", line 102, in load_dataframe
    content = all_content(directory_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\generate_link_lists.py", line 92, in all_content
    new_content = read_yaml_file(directory_path + filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\generate_link_lists.py", line 120, in read_yaml_file
    with open(filename, 'r', encoding="utf8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '..\\resourcesnfdi4bioimage.yml'
2024-09-04 13:10:58.472 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\huang\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\huang\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\huang\Documents\GitHub\training\scripts\appsubmitter.py", line 120, in <module>
    unique_tags, unique_types, unique_licenses = get_unique_values_from_yamls(directory_path)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\appsubmitter.py", line 44, in get_unique_values_from_yamls
    df = load_dataframe(resources_dir)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\generate_link_lists.py", line 102, in load_dataframe
    content = all_content(directory_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\generate_link_lists.py", line 92, in all_content
    new_content = read_yaml_file(directory_path + filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\Documents\GitHub\training\scripts\generate_link_lists.py", line 120, in read_yaml_file
    with open(filename, 'r', encoding="utf8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '..\\resourcesnfdi4bioimage.yml'

**Comment by SeverusYixin** [comment]
maybe with os.path.join()?

**Comment by haesleinhuepf** [comment]
Did you try this?

**Comment by SeverusYixin** [comment]
no, because that's need to change the code in "generate_link_lists.py".

**Comment by haesleinhuepf** [comment]
Changing files is a normal thing. Give it a try.

**Comment by SeverusYixin** [comment]
ok, that's more easy that I can update it 👍

**Comment by haesleinhuepf** [comment]
Are there any news on this @SeverusYixin ?

**Comment by SeverusYixin** [comment]
Hi @haesleinhuepf, this one also finished.

**Comment by haesleinhuepf** [comment]
True! 
Done in #128
